In [2]:
import numpy as np
import matplotlib.pyplot as plt 

## 1 - **np.unravel()**


Converts a flat index or array of flat indices into a tuple

In [26]:
np.unravel_index(120,(12,13)) # 

(9, 3)

## 2 - np.argmin()

Returns the indices of the minimum values along an axis.

In [27]:
array=np.random.randint(12,size=12).reshape(3,4)
array

array([[ 8, 10,  7,  4],
       [11,  8,  8,  0],
       [ 8,  9,  9, 11]])

In [28]:
np.argmin(array,axis=0)

array([0, 1, 0, 1])

In [29]:
np.argmin(array,axis=1)

array([3, 3, 0])

In [30]:
np.argmin(array) # starting  is "0"

7

## 3 - np.tile()

Construct an array by repeating A the number of times given by reps.

In [47]:
# np.tile(A, reps)

np.tile([1,2],(4,1))

array([[1, 2],
       [1, 2],
       [1, 2],
       [1, 2]])

## 4 - np.linalg.norm()

Matrix or vector norm.

In [34]:
array=np.array([[2,1],[2,1]])
array

array([[2, 1],
       [2, 1]])

In [40]:
# np.linalg.norm(x, ord=None, axis=None, keepdims=False)

np.linalg.norm(array) # all

3.1622776601683795

In [41]:
np.linalg.norm(array,axis=1) # y axis

array([2.23606798, 2.23606798])

In [42]:
np.linalg.norm(array,axis=0) # x axis

array([2.82842712, 1.41421356])

## 5 -  np.flip()

Reverse the order of elements in an array along the given axis.

In [53]:
a = np.arange(8).reshape((2,4))
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [57]:
# np.flip(m, axis=None)

np.flip(a,0)

array([[4, 5, 6, 7],
       [0, 1, 2, 3]])

In [58]:
np.flip(a,1)

array([[3, 2, 1, 0],
       [7, 6, 5, 4]])